Change behaviour of `noPeers` event
webtorrent/webtorrent pull request #2142
Opened 2021-07-21 00:30 UTC by alxhotel

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
This PR:
- Changes the behaviour of the `noPeers` event
- Adds a new option to the client constructor to disable `ut_pex` discovery mechanism
- Refactor `Peer` constants

**Which issue (if any) does this pull request address?**
Closes #1622

**Is there anything you'd like reviewers to focus on?**

**Note**: This is a breaking change so it should be merged to v2 branch.

2021-07-21 22:55 UTC, DiegoRBaquero commented on lib/torrent.js
> +const NO_PEERS_INTERVAL = 30_000 // 30 seconds
shouldn't this be an opt in the client? defaulted to 30 seconds

2021-07-21 22:56 UTC, DiegoRBaquero approved these changes
I don't think this needs to be a breaking change major version, at least one event is being emitted now

2021-07-23 16:35 UTC, DiegoRBaquero requested changes
opts states seconds, so we must multiply

2021-07-23 16:35 UTC, DiegoRBaquero commented on lib/torrent.js
> +    this._noPeersIntervalTime = opts.noPeersIntervalTime || DEFAULT_NO_PEERS_INTERVAL
```suggestion
    this._noPeersIntervalTime = opts.noPeersIntervalTime ? opts.noPeersIntervalTime * 1000 : DEFAULT_NO_PEERS_INTERVAL
```

2021-07-23 16:47 UTC, alxhotel commented on lib/torrent.js
> +    this._noPeersIntervalTime = opts.noPeersIntervalTime || DEFAULT_NO_PEERS_INTERVAL
Oh good catch!

2021-07-23 17:14 UTC, DiegoRBaquero approved these changes

2021-07-23 17:27 UTC, merged

2025-01-21 21:10 UTC, ThaUnknown commented
why do incoming peers not have a source?